
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const App = lazy(() => import("./pages/App.tsx"));
const Curriculum = lazy(() => import("./pages/Curriculum.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const FacultyDashboard = lazy(() => import("./pages/FacultyDashboard.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const Quiz = lazy(() => import("./pages/Quiz.tsx"));
const Register = lazy(() => import("./pages/Register.tsx"));
const VirtualAssistant = lazy(() => import("./pages/VirtualAssistant.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/curriculum", element: <UserGuard><Curriculum /></UserGuard>},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/faculty-dashboard", element: <UserGuard><FacultyDashboard /></UserGuard>},
	{ path: "/facultydashboard", element: <UserGuard><FacultyDashboard /></UserGuard>},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/profile", element: <UserGuard><Profile /></UserGuard>},
	{ path: "/quiz", element: <UserGuard><Quiz /></UserGuard>},
	{ path: "/register", element: <UserGuard><Register /></UserGuard>},
	{ path: "/virtual-assistant", element: <UserGuard><VirtualAssistant /></UserGuard>},
	{ path: "/virtualassistant", element: <UserGuard><VirtualAssistant /></UserGuard>},

];
